export const NOMINA_CONSTANTS = {
    MESES_ANIO: 12,
    DIVISOR_VACACIONES: 24,
    SBU_DEFAULT: 460.00,
    APORTE_PERSONAL_DEFAULT: 9.45,
    APORTE_PATRONAL_DEFAULT: 12.15,
    FONDO_RESERVA_PORCENTAJE_DEFAULT: 8.33,
};
